### PR TITLE
Fixed bug with titles that have space replaced with + issue #4

### PR DESCRIPTION
**Pull request by OsamaYousry**
I've fixed this bug, and am planning to work more on adding more features for the code, tell me what you think!

### CODE REVIEW

**Comment by czerwinskilukasz1** [comment]
Ryan, I'm also interested in seeing this bug fixed. Any plans on applying this change?
Thanks!

**Comment by ryanrolds** [comment]
Sorry for being late to the party. I will review in the next couple of days,. Thank you both for your patience.

**Comment by ryanrolds** [comment]
@OsamaYousry Overall looks good. Needs to have a couple things before I will merge and release.

* Tests for the new methods and other changes
* A few functions were added and the README.md was not updated (except for one).

**Comment by OsamaYousry** [comment]
@ryanrolds I added the test and the two functions in the README file, Is this okay?

**Comment by ryanrolds** [comment]
:+1:

**Comment by ryanrolds** [comment]
Released as version 0.1.0.

**Pull request merged**
